---

- name: Run apt-get update if the last one is more than 1h ago
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'
  tags:
    - apt

- name: Decrease timeout to skip unreachable servers faster
  copy:
    src: 99timeout
    dest: /etc/apt/apt.conf.d/99timeout
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'
  tags:
    - apt

- name: Activate Ubuntu partner repository
  apt_repository:
    repo: "deb http://archive.canonical.com/ubuntu {{ansible_distribution_release | lower}} partner"
    state: present
  when: ansible_distribution == 'Ubuntu'
  tags:
    - apt

- name: Erase installed packages
  apt:
    name: "{{item}}"
    state: absent
  with_items: "{{apt_packages_erase}}"
  when: ansible_os_family == 'Debian'
  tags:
    - apt
    - packages

- name: Install packages
  apt:
    name: "{{item}}"
    state: present
  with_items: "{{apt_packages_install}}"
  when: ansible_os_family == 'Debian'
  tags:
    - apt
    - packages
